import { config } from "dotenv";
config({ path: ".env.local" });

import type { NewProperty } from "../schema";

function placeholderImages(slug: string, count: number) {
  return Array.from(
    { length: count },
    (_, i) => `https://picsum.photos/seed/${slug}-${i}/1200/800`
  );
}

const SAMPLE_PROPERTIES: NewProperty[] = [
  {
    title: "Skyline Residency",
    slug: "skyline-residency-bandra",
    location: "Bandra West, Mumbai",
    shortLocation: "Bandra West",
    propertyType: "Residential Apartment",
    description:
      "A premium residential tower in the heart of Bandra West, offering fractional ownership in a fully-leased apartment block with strong rental demand from young professionals.",
    totalValuation: "50000000",
    fundingTarget: "50000000",
    amountRaised: "31500000",
    minInvestment: "250000",
    estAnnualYield: "9.5",
    investmentHorizon: "5 years",
    fundingDeadline: "2026-10-15",
    status: "fundraising",
    images: placeholderImages("skyline-residency-bandra", 4),
    amenities: ["24/7 Security", "Power Backup", "Covered Parking", "Gym"],
    bedrooms: 3,
    areaSqft: "1850",
    possessionStatus: "Ready to Move-in",
    projectedAppreciation: "9.5",
    tags: ["Premium Location", "High Rental Demand", "Vetted Property"],
  },
  {
    title: "Whitefield Tech Park Suites",
    slug: "whitefield-tech-park-suites",
    location: "Whitefield, Bangalore",
    shortLocation: "Whitefield",
    propertyType: "Commercial Office",
    description:
      "Grade-A office suites leased to IT tenants near Bangalore's tech corridor, generating stable long-term rental income with annual escalation clauses.",
    totalValuation: "80000000",
    fundingTarget: "80000000",
    amountRaised: "80000000",
    minInvestment: "500000",
    estAnnualYield: "11",
    investmentHorizon: "7 years",
    fundingDeadline: "2026-04-01",
    status: "fully_funded",
    images: placeholderImages("whitefield-tech-park-suites", 5),
    amenities: ["Cafeteria", "Conference Rooms", "High-Speed Internet", "Parking"],
    bedrooms: null,
    areaSqft: "12000",
    possessionStatus: "Ready to Move-in",
    projectedAppreciation: "7.5",
    tags: ["Grade-A Office", "Anchor Leased", "Vetted Property"],
  },
  {
    title: "Koregaon Park Villas",
    slug: "koregaon-park-villas",
    location: "Koregaon Park, Pune",
    shortLocation: "Koregaon Park",
    propertyType: "Villa",
    description:
      "A gated community of luxury villas in one of Pune's most sought-after neighborhoods, ideal for long-term capital appreciation.",
    totalValuation: "35000000",
    fundingTarget: "35000000",
    amountRaised: "12250000",
    minInvestment: "200000",
    estAnnualYield: "8",
    investmentHorizon: "6 years",
    fundingDeadline: "2026-12-20",
    status: "fundraising",
    images: placeholderImages("koregaon-park-villas", 4),
    amenities: ["Private Garden", "Clubhouse", "Swimming Pool", "24/7 Security"],
    bedrooms: 4,
    areaSqft: "3200",
    possessionStatus: "Ready to Move-in",
    projectedAppreciation: "10",
    tags: ["Gated Community", "Premium Location", "High Appreciation"],
  },
  {
    title: "Cyber City Business Hub",
    slug: "cyber-city-business-hub",
    location: "DLF Cyber City, Gurgaon",
    shortLocation: "DLF Cyber City",
    propertyType: "Commercial Office",
    description:
      "A multi-tenant commercial building in DLF Cyber City with a diversified tenant mix across fintech and consulting firms.",
    totalValuation: "120000000",
    fundingTarget: "120000000",
    amountRaised: "45000000",
    minInvestment: "500000",
    estAnnualYield: "10.5",
    investmentHorizon: "7 years",
    fundingDeadline: "2026-11-30",
    status: "fundraising",
    images: placeholderImages("cyber-city-business-hub", 5),
    amenities: ["Food Court", "Conference Rooms", "EV Charging", "Metro Connectivity"],
    bedrooms: null,
    areaSqft: "25000",
    possessionStatus: "Ready to Move-in",
    projectedAppreciation: "8",
    tags: ["Prime Business District", "Diversified Tenants", "Vetted Property"],
  },
  {
    title: "Candolim Beachside Residences",
    slug: "candolim-beachside-residences",
    location: "Candolim, Goa",
    shortLocation: "Candolim",
    propertyType: "Holiday Rental",
    description:
      "A boutique holiday-rental property near Candolim beach, generating income through short-term vacation rentals managed by a professional operator.",
    totalValuation: "28000000",
    fundingTarget: "28000000",
    amountRaised: "28000000",
    minInvestment: "150000",
    estAnnualYield: "12",
    investmentHorizon: "5 years",
    fundingDeadline: "2026-02-28",
    status: "closed",
    images: placeholderImages("candolim-beachside-residences", 4),
    amenities: ["Private Pool", "Beach Access", "Housekeeping", "Managed Rentals"],
    bedrooms: 2,
    areaSqft: "1400",
    possessionStatus: "Ready to Move-in",
    projectedAppreciation: "11",
    tags: ["Beachfront", "High Rental Demand", "Managed Property"],
  },
  {
    title: "Gachibowli Financial Square",
    slug: "gachibowli-financial-square",
    location: "Gachibowli, Hyderabad",
    shortLocation: "Gachibowli",
    propertyType: "Commercial Office",
    description:
      "A modern office complex in Hyderabad's financial district, anchor-leased to a Fortune 500 tenant on a long-term lease.",
    totalValuation: "95000000",
    fundingTarget: "95000000",
    amountRaised: "20000000",
    minInvestment: "500000",
    estAnnualYield: "10",
    investmentHorizon: "8 years",
    fundingDeadline: "2027-01-15",
    status: "fundraising",
    images: placeholderImages("gachibowli-financial-square", 4),
    amenities: ["Anchor Tenant", "Cafeteria", "Parking", "Backup Power"],
    bedrooms: null,
    areaSqft: "18000",
    possessionStatus: "Under Construction",
    projectedAppreciation: "9",
    tags: ["Anchor Tenant", "Financial District", "Vetted Property"],
  },
  {
    title: "Adyar Riverside Apartments",
    slug: "adyar-riverside-apartments",
    location: "Adyar, Chennai",
    shortLocation: "Adyar",
    propertyType: "Residential Apartment",
    description:
      "A mid-rise residential development along the Adyar riverside, popular with families and long-term tenants for its central location.",
    totalValuation: "42000000",
    fundingTarget: "42000000",
    amountRaised: "6300000",
    minInvestment: "200000",
    estAnnualYield: "8.5",
    investmentHorizon: "6 years",
    fundingDeadline: "2026-09-10",
    status: "fundraising",
    images: placeholderImages("adyar-riverside-apartments", 4),
    amenities: ["River View", "Gym", "Children's Play Area", "Covered Parking"],
    bedrooms: 3,
    areaSqft: "1650",
    possessionStatus: "Ready to Move-in",
    projectedAppreciation: "8.5",
    tags: ["River View", "Family-Friendly", "High Rental Demand"],
  },
  {
    title: "Powai Lakeview Towers",
    slug: "powai-lakeview-towers",
    location: "Powai, Mumbai",
    shortLocation: "Powai",
    propertyType: "Residential Apartment",
    description:
      "A premium high-rise overlooking Powai Lake, popular with IT professionals working in the nearby business parks and known for consistently strong occupancy.",
    totalValuation: "62000000",
    fundingTarget: "62000000",
    amountRaised: "18600000",
    minInvestment: "300000",
    estAnnualYield: "9",
    investmentHorizon: "6 years",
    fundingDeadline: "2026-11-05",
    status: "fundraising",
    images: placeholderImages("powai-lakeview-towers", 4),
    amenities: ["Lake View", "Clubhouse", "Gym", "24/7 Security"],
    bedrooms: 2,
    areaSqft: "1200",
    possessionStatus: "Ready to Move-in",
    projectedAppreciation: "9.5",
    tags: ["Lake View", "High Rental Demand", "Vetted Property"],
  },
  {
    title: "Electronic City Innovation Park",
    slug: "electronic-city-innovation-park",
    location: "Electronic City, Bangalore",
    shortLocation: "Electronic City",
    propertyType: "Commercial Office",
    description:
      "A Grade-A IT park leased to a mix of multinational technology tenants, offering stable rental yields backed by long-term lock-in agreements.",
    totalValuation: "105000000",
    fundingTarget: "105000000",
    amountRaised: "52500000",
    minInvestment: "500000",
    estAnnualYield: "11.5",
    investmentHorizon: "8 years",
    fundingDeadline: "2027-02-10",
    status: "fundraising",
    images: placeholderImages("electronic-city-innovation-park", 5),
    amenities: ["Food Court", "EV Charging", "Conference Rooms", "Parking"],
    bedrooms: null,
    areaSqft: "20000",
    possessionStatus: "Ready to Move-in",
    projectedAppreciation: "8.5",
    tags: ["Grade-A Office", "MNC Tenants", "Vetted Property"],
  },
  {
    title: "Baner Hilltop Residences",
    slug: "baner-hilltop-residences",
    location: "Baner, Pune",
    shortLocation: "Baner",
    propertyType: "Residential Apartment",
    description:
      "A modern residential complex in Pune's fast-growing Baner corridor, close to IT hubs and popular among young working professionals seeking rental housing.",
    totalValuation: "38000000",
    fundingTarget: "38000000",
    amountRaised: "9500000",
    minInvestment: "200000",
    estAnnualYield: "8.5",
    investmentHorizon: "5 years",
    fundingDeadline: "2026-10-25",
    status: "fundraising",
    images: placeholderImages("baner-hilltop-residences", 4),
    amenities: ["Gym", "Swimming Pool", "Covered Parking", "Power Backup"],
    bedrooms: 2,
    areaSqft: "1100",
    possessionStatus: "Ready to Move-in",
    projectedAppreciation: "9",
    tags: ["Growth Corridor", "High Rental Demand", "Vetted Property"],
  },
  {
    title: "Golf Course Road Executive Towers",
    slug: "golf-course-road-executive-towers",
    location: "Golf Course Road, Gurgaon",
    shortLocation: "Golf Course Road",
    propertyType: "Commercial Office",
    description:
      "An iconic office tower on Gurgaon's Golf Course Road, anchor-leased to a global consulting firm with a fifteen-year lease and built-in rent escalations.",
    totalValuation: "150000000",
    fundingTarget: "150000000",
    amountRaised: "150000000",
    minInvestment: "1000000",
    estAnnualYield: "12",
    investmentHorizon: "10 years",
    fundingDeadline: "2026-03-01",
    status: "fully_funded",
    images: placeholderImages("golf-course-road-executive-towers", 5),
    amenities: ["Anchor Tenant", "Cafeteria", "Valet Parking", "Backup Power"],
    bedrooms: null,
    areaSqft: "30000",
    possessionStatus: "Ready to Move-in",
    projectedAppreciation: "8",
    tags: ["Anchor Tenant", "Prime Business District", "Vetted Property"],
  },
  {
    title: "Anjuna Hillside Villas",
    slug: "anjuna-hillside-villas",
    location: "Anjuna, Goa",
    shortLocation: "Anjuna",
    propertyType: "Holiday Rental",
    description:
      "A collection of boutique hillside villas near Anjuna's beaches and flea market, operated as a managed short-term rental portfolio for tourists.",
    totalValuation: "32000000",
    fundingTarget: "32000000",
    amountRaised: "8000000",
    minInvestment: "150000",
    estAnnualYield: "13",
    investmentHorizon: "5 years",
    fundingDeadline: "2026-12-05",
    status: "fundraising",
    images: placeholderImages("anjuna-hillside-villas", 4),
    amenities: ["Private Pool", "Hillside View", "Housekeeping", "Managed Rentals"],
    bedrooms: 3,
    areaSqft: "1800",
    possessionStatus: "Ready to Move-in",
    projectedAppreciation: "11.5",
    tags: ["Holiday Destination", "High Rental Demand", "Managed Property"],
  },
  {
    title: "HITEC City Corporate Center",
    slug: "hitec-city-corporate-center",
    location: "HITEC City, Hyderabad",
    shortLocation: "HITEC City",
    propertyType: "Commercial Office",
    description:
      "A landmark corporate center in Hyderabad's HITEC City, home to a diversified mix of technology and BFSI tenants with staggered lease expiries.",
    totalValuation: "88000000",
    fundingTarget: "88000000",
    amountRaised: "26400000",
    minInvestment: "500000",
    estAnnualYield: "10.5",
    investmentHorizon: "7 years",
    fundingDeadline: "2026-09-18",
    status: "fundraising",
    images: placeholderImages("hitec-city-corporate-center", 4),
    amenities: ["Food Court", "Conference Rooms", "Metro Connectivity", "Parking"],
    bedrooms: null,
    areaSqft: "16500",
    possessionStatus: "Ready to Move-in",
    projectedAppreciation: "8.5",
    tags: ["Diversified Tenants", "Financial District", "Vetted Property"],
  },
  {
    title: "Anna Nagar Garden Homes",
    slug: "anna-nagar-garden-homes",
    location: "Anna Nagar, Chennai",
    shortLocation: "Anna Nagar",
    propertyType: "Residential Apartment",
    description:
      "A well-established residential enclave in Anna Nagar with a track record of steady appreciation and dependable long-term tenants.",
    totalValuation: "45000000",
    fundingTarget: "45000000",
    amountRaised: "45000000",
    minInvestment: "250000",
    estAnnualYield: "8",
    investmentHorizon: "6 years",
    fundingDeadline: "2026-01-20",
    status: "closed",
    images: placeholderImages("anna-nagar-garden-homes", 4),
    amenities: ["Garden", "Gym", "Covered Parking", "24/7 Security"],
    bedrooms: 3,
    areaSqft: "1750",
    possessionStatus: "Ready to Move-in",
    projectedAppreciation: "8.5",
    tags: ["Established Neighborhood", "Family-Friendly", "Vetted Property"],
  },
  {
    title: "Vasant Kunj Signature Residences",
    slug: "vasant-kunj-signature-residences",
    location: "Vasant Kunj, New Delhi",
    shortLocation: "Vasant Kunj",
    propertyType: "Residential Apartment",
    description:
      "An upscale residential development in South Delhi's Vasant Kunj, favored by diplomats and senior executives for its greenery and connectivity.",
    totalValuation: "72000000",
    fundingTarget: "72000000",
    amountRaised: "21600000",
    minInvestment: "400000",
    estAnnualYield: "8",
    investmentHorizon: "6 years",
    fundingDeadline: "2026-10-30",
    status: "fundraising",
    images: placeholderImages("vasant-kunj-signature-residences", 4),
    amenities: ["Landscaped Gardens", "Clubhouse", "Gym", "24/7 Security"],
    bedrooms: 3,
    areaSqft: "2100",
    possessionStatus: "Ready to Move-in",
    projectedAppreciation: "9",
    tags: ["Premium Location", "High Appreciation", "Vetted Property"],
  },
  {
    title: "Sector 62 Noida Business Park",
    slug: "sector-62-noida-business-park",
    location: "Sector 62, Noida",
    shortLocation: "Sector 62",
    propertyType: "Commercial Office",
    description:
      "A well-connected IT/ITES office park in Noida's Sector 62 corridor, leased to established outsourcing and technology firms.",
    totalValuation: "68000000",
    fundingTarget: "68000000",
    amountRaised: "13600000",
    minInvestment: "350000",
    estAnnualYield: "11",
    investmentHorizon: "7 years",
    fundingDeadline: "2027-01-05",
    status: "fundraising",
    images: placeholderImages("sector-62-noida-business-park", 4),
    amenities: ["Food Court", "Metro Connectivity", "Parking", "Backup Power"],
    bedrooms: null,
    areaSqft: "14000",
    possessionStatus: "Under Construction",
    projectedAppreciation: "9.5",
    tags: ["IT Corridor", "Metro Connectivity", "Vetted Property"],
  },
  {
    title: "Salt Lake Sector V Tech Towers",
    slug: "salt-lake-sector-v-tech-towers",
    location: "Sector V, Kolkata",
    shortLocation: "Sector V",
    propertyType: "Commercial Office",
    description:
      "A modern tech park in Kolkata's Sector V IT hub, home to a mix of domestic IT companies and back-office operations with strong occupancy history.",
    totalValuation: "54000000",
    fundingTarget: "54000000",
    amountRaised: "16200000",
    minInvestment: "300000",
    estAnnualYield: "10",
    investmentHorizon: "6 years",
    fundingDeadline: "2026-11-22",
    status: "fundraising",
    images: placeholderImages("salt-lake-sector-v-tech-towers", 4),
    amenities: ["Cafeteria", "Conference Rooms", "Parking", "Power Backup"],
    bedrooms: null,
    areaSqft: "11000",
    possessionStatus: "Ready to Move-in",
    projectedAppreciation: "8",
    tags: ["IT Hub", "Stable Occupancy", "Vetted Property"],
  },
  {
    title: "Malviya Nagar Heritage Court",
    slug: "malviya-nagar-heritage-court",
    location: "Malviya Nagar, Jaipur",
    shortLocation: "Malviya Nagar",
    propertyType: "Residential Apartment",
    description:
      "A centrally located residential project in Jaipur's Malviya Nagar, benefiting from proximity to the airport and major commercial hubs.",
    totalValuation: "26000000",
    fundingTarget: "26000000",
    amountRaised: "5200000",
    minInvestment: "150000",
    estAnnualYield: "8.5",
    investmentHorizon: "5 years",
    fundingDeadline: "2026-12-12",
    status: "fundraising",
    images: placeholderImages("malviya-nagar-heritage-court", 4),
    amenities: ["Gym", "Children's Play Area", "Covered Parking", "24/7 Security"],
    bedrooms: 2,
    areaSqft: "1300",
    possessionStatus: "Ready to Move-in",
    projectedAppreciation: "9",
    tags: ["Airport Proximity", "Growth Corridor", "Vetted Property"],
  },
  {
    title: "SG Highway Corporate Plaza",
    slug: "sg-highway-corporate-plaza",
    location: "SG Highway, Ahmedabad",
    shortLocation: "SG Highway",
    propertyType: "Commercial Office",
    description:
      "A prominent commercial plaza on Ahmedabad's SG Highway, leased to a diversified mix of banking, retail, and corporate tenants.",
    totalValuation: "58000000",
    fundingTarget: "58000000",
    amountRaised: "58000000",
    minInvestment: "300000",
    estAnnualYield: "10.5",
    investmentHorizon: "7 years",
    fundingDeadline: "2026-02-14",
    status: "fully_funded",
    images: placeholderImages("sg-highway-corporate-plaza", 4),
    amenities: ["Food Court", "Conference Rooms", "Parking", "Backup Power"],
    bedrooms: null,
    areaSqft: "13000",
    possessionStatus: "Ready to Move-in",
    projectedAppreciation: "8",
    tags: ["Diversified Tenants", "Prime Business District", "Vetted Property"],
  },
  {
    title: "Marine Drive Panoramic Suites",
    slug: "marine-drive-panoramic-suites",
    location: "Marine Drive, Kochi",
    shortLocation: "Marine Drive",
    propertyType: "Residential Apartment",
    description:
      "A waterfront residential tower along Kochi's Marine Drive offering panoramic backwater views, popular with NRI buyers and long-term renters.",
    totalValuation: "40000000",
    fundingTarget: "40000000",
    amountRaised: "10000000",
    minInvestment: "200000",
    estAnnualYield: "8",
    investmentHorizon: "6 years",
    fundingDeadline: "2026-11-15",
    status: "fundraising",
    images: placeholderImages("marine-drive-panoramic-suites", 4),
    amenities: ["Waterfront View", "Gym", "Clubhouse", "Covered Parking"],
    bedrooms: 3,
    areaSqft: "1900",
    possessionStatus: "Under Construction",
    projectedAppreciation: "9.5",
    tags: ["Waterfront", "NRI Favorite", "High Appreciation"],
  },
];

async function seed() {
  // Dynamic imports so `config()` above runs before `../client` reads
  // process.env.DATABASE_URL — static imports would otherwise be hoisted
  // ahead of it.
  const { db } = await import("../client");
  const { properties } = await import("../schema");
  const { sql } = await import("drizzle-orm");

  console.log(`Seeding ${SAMPLE_PROPERTIES.length} properties...`);

  await db
    .insert(properties)
    .values(SAMPLE_PROPERTIES)
    .onConflictDoUpdate({
      target: properties.slug,
      set: {
        title: sql`excluded.title`,
        location: sql`excluded.location`,
        shortLocation: sql`excluded.short_location`,
        propertyType: sql`excluded.property_type`,
        description: sql`excluded.description`,
        totalValuation: sql`excluded.total_valuation`,
        fundingTarget: sql`excluded.funding_target`,
        minInvestment: sql`excluded.min_investment`,
        estAnnualYield: sql`excluded.est_annual_yield`,
        investmentHorizon: sql`excluded.investment_horizon`,
        fundingDeadline: sql`excluded.funding_deadline`,
        status: sql`excluded.status`,
        images: sql`excluded.images`,
        amenities: sql`excluded.amenities`,
        bedrooms: sql`excluded.bedrooms`,
        areaSqft: sql`excluded.area_sqft`,
        possessionStatus: sql`excluded.possession_status`,
        projectedAppreciation: sql`excluded.projected_appreciation`,
        tags: sql`excluded.tags`,
      },
    });

  console.log("Seed complete.");
  process.exit(0);
}

seed().catch((error) => {
  console.error("Seed failed:", error);
  process.exit(1);
});
